[general]
output_dir = 'outputs/audiocaps/whitebox/imagebind/'
model_flag = 'imagebind'
gpu_num = 0
epochs = 7500
batch_size = 4
epsilon = 1e-1
lr = 0.02
seed = 0
number_images = 100
gamma_epochs = 200
modality = 'audio'
dataset_flag = 'audiocaps'
