[general]
embeddings_input = "outputs/embeddings/imagenet_imagebind_embeddings.npy"
output_dir = "outputs/imagenet/query/imagebind/"
model_flag = "imagebind_full"
gpu_num = 0
epochs = 100000
batch_size = 100
epsilon = 16
zero_shot_steps = 1
lr = 0.02
eta_min = 1e-5
seed = 0
number_images = 100
buffer_size = 10
delta = 0.0
gamma_epochs = 300